apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tekton-builds
  name: ace-deployment
  labels:
    app: ace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ace
  template:
    metadata:
      labels:
        app: ace
    spec:
      containers:
      - name: ace
        image: 736505676141.dkr.ecr.us-east-2.amazonaws.com/ace-test:effea1643da97f0c1d1b618a387fde3f6eade127
        imagePullPolicy: Always
        ports:
        - containerPort: 7600
      imagePullSecrets:
      - name: ecr-cred
---

apiVersion: v1
kind: Service
metadata:
  namespace: tekton-builds
  name: ace-service
spec:
  selector:
    app: ace
  ports:
    - name: http
      protocol: TCP
      port: 3002
      targetPort: 7600
      nodePort: 30001
#  externalIPs:
#    - 192.168.100.95
  type: NodePort
