apiVersion: apps/v1
kind: Deployment
metadata:
  name: ace-deployment
  labels:
    app: node-farhan
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ace
  template:
    metadata:
      labels:
        app: ace
    spec:
      containers:
      - name: ace
        image: mfarhan1998/ace-test:51
        imagePullPolicy: Always
        ports:
        - containerPort: 7600

---

apiVersion: v1
kind: Service
metadata:
  name: ace-service
spec:
  selector:
    app: ace
  ports:
    - name: http
      protocol: TCP
      port: 3002
      targetPort: 7600
      nodePort: 30001
  externalIPs:
    - 52.146.37.196
  type: NodePort
