# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: AppConnect
  
steps:
- task: BatchScript@1
  inputs:
    filename: 'C:\Program Files\IBM\ACE\11.0.0.8\server\bin\mqsiprofile.cmd'
    modifyEnvironment: true
- task: IBMIntegrationBusDeploy@1
  inputs:
    barPath: '**/*.bar'
    iibEndpoint: 'app-connect'
    integrationServerName: 'test-eg'
    completeDeployment: true