# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: AppConnect
  
steps:
- task: BatchScript@1
  inputs:
    filename: 'C:\Program Files\IBM\ACE\11.0.0.8\server\bin\mqsiprofile.cmd'
    modifyEnvironment: true
    
- task: IBMIntegrationBusCommand@1
  inputs:
    iibEndpoint: 'app-connect'
    cmd: 'mqsicreatebar'
    args: '-data $(Build.Repository.LocalPath) -b $(Build.Repository.LocalPath)\Hello_$(Build.BuildID).bar -a HelloWorld -deployAsSource -v createbartrace.txt -cleanBuild'
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub-connection'
    repository: 'mfarhan1998/ace-test'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- task: IBMIntegrationBusDeploy@1
  inputs:
    barPath: '**/Hello_$(Build.BuildID).bar'
    iibEndpoint: 'app-connect'
    integrationServerName: 'test-eg'
    completeDeployment: true
    